"""ArticleTag + Articles Fix

Revision ID: 2299deb080ba
Revises: 2ed6fb0d0f09
Create Date: 2025-11-23 20:37:51.850917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2299deb080ba'
down_revision: Union[str, Sequence[str], None] = '2ed6fb0d0f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
