"""Users Table Fix 1

Revision ID: 51fd7edd7dbd
Revises: 55865ab45c40
Create Date: 2025-11-25 20:36:16.836646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51fd7edd7dbd'
down_revision: Union[str, Sequence[str], None] = '55865ab45c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('real_name', sa.String(length=25), nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.drop_column('users', 'real_name')
    # ### end Alembic commands ###
