"""Users Table Fix

Revision ID: 55865ab45c40
Revises: 2299deb080ba
Create Date: 2025-11-25 20:24:50.299221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55865ab45c40'
down_revision: Union[str, Sequence[str], None] = '2299deb080ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    # ### end Alembic commands ###
